# system configuration
system:
  addr: 8888
  #  路由全局前缀
  router-prefix: "api"

mysql:
  path: "162.14.72.99"
  port: "3306"
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db-name: "ly-server"
  username: "root"
  password: "root@mysql"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "info"
  log-zap: True